{
 "title": "Metrics Example",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "go_memstats_alloc_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Go Routines",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Go Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 8 },
   "targets": [
    { "expr": "go_info", "legendFormat": "{{instance}}: {{version}}" }
   ]
  },
  {
   "title": "go_gc_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=\"app:8080\"}"
    }
   ]
  },
  {
   "title": "go_gc_duration_seconds_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds_count{instance=\"app:8080\"}"
    }
   ]
  }
 ]
}